import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import type { CategoryRow, ComplianceResult, ComponentInput } from '$lib/compliance/types';

export interface CertificateInput {
  projectName: string;
  trialVersionLabel: string;
  targetCategory: CategoryRow;
  compoundDosagePct: number;
  amendmentVersion: string;
  amendmentIsStarter: boolean;
  components: Array<{
    name: string;
    cas: string | null;
    partsPer1000: number;
    dilutionPct: number;
  }>;
  engineComponents: ComponentInput[];
  complianceResult: ComplianceResult;
  categories: CategoryRow[];
  generatedAt: Date;
}

const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;
const MARGIN = 40;

interface Cursor {
  page: PDFPage;
  y: number;
}

function newPage(doc: PDFDocument, font: PDFFont, bold: PDFFont, footerText: string): Cursor {
  const page = doc.addPage([PAGE_W, PAGE_H]);
  const cursor: Cursor = { page, y: PAGE_H - MARGIN };
  // Footer
  page.drawText(footerText, {
    x: MARGIN,
    y: 20,
    size: 8,
    font,
    color: rgb(0.4, 0.4, 0.4)
  });
  return cursor;
}

function ensure(c: Cursor, doc: PDFDocument, font: PDFFont, bold: PDFFont, footer: string, needed: number) {
  if (c.y - needed < MARGIN + 30) {
    Object.assign(c, newPage(doc, font, bold, footer));
  }
}

function text(c: Cursor, str: string, font: PDFFont, size: number, color = rgb(0, 0, 0)) {
  c.page.drawText(str, { x: MARGIN, y: c.y, size, font, color });
}

function textAt(c: Cursor, x: number, str: string, font: PDFFont, size: number, color = rgb(0, 0, 0)) {
  c.page.drawText(str, { x, y: c.y, size, font, color });
}

function line(c: Cursor) {
  c.page.drawLine({
    start: { x: MARGIN, y: c.y },
    end: { x: PAGE_W - MARGIN, y: c.y },
    thickness: 0.5,
    color: rgb(0.7, 0.7, 0.7)
  });
}

function pp1000ToPct(pp: number): number {
  return pp / 10;
}

function fmtPct(v: number | null | undefined): string {
  if (v == null) return '—';
  if (v === 0) return '0%';
  if (v < 0.001) return v.toExponential(1) + '%';
  if (v < 0.1) return v.toFixed(3) + '%';
  if (v < 1) return v.toFixed(2) + '%';
  if (v < 10) return v.toFixed(1) + '%';
  return Math.round(v) + '%';
}

export async function generateCertificate(input: CertificateInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  const footer = `Generated by IFrag · ${input.generatedAt.toISOString().slice(0, 19).replace('T', ' ')} · Active amendment: ${input.amendmentVersion}${input.amendmentIsStarter ? ' (STARTER — not official)' : ''}`;
  let cur = newPage(doc, font, bold, footer);

  // Title
  text(cur, 'IFRA CONFORMITY CERTIFICATE', bold, 16);
  cur.y -= 22;
  text(cur, `Project: ${input.projectName}`, font, 11);
  cur.y -= 14;
  text(cur, `Formula version: ${input.trialVersionLabel}`, font, 11);
  cur.y -= 14;
  text(
    cur,
    `Target IFRA category: Cat ${input.targetCategory.code} — ${input.targetCategory.label}`,
    font,
    11
  );
  cur.y -= 14;
  text(
    cur,
    `Compound dosage in finished product: ${input.compoundDosagePct.toFixed(1)}%`,
    font,
    11
  );
  cur.y -= 14;
  text(cur, `IFRA amendment used: ${input.amendmentVersion}`, font, 11);
  cur.y -= 14;
  if (input.amendmentIsStarter) {
    text(
      cur,
      'WARNING: this certificate was produced against a starter dataset. Re-issue against the official IFRA standards before commercial use.',
      bold,
      9,
      rgb(0.7, 0.2, 0.1)
    );
    cur.y -= 14;
  }
  cur.y -= 8;
  line(cur);
  cur.y -= 16;

  // Summary verdict at target category
  const targetVerdict = input.complianceResult.perCategory.get(input.targetCategory.number);
  const verdictWord =
    targetVerdict?.status === 'pass'
      ? 'CONFORMS'
      : targetVerdict?.status === 'warn'
        ? 'CONFORMS WITH NOTES'
        : targetVerdict?.status === 'fail'
          ? 'DOES NOT CONFORM'
          : 'UNKNOWN';
  const verdictColor =
    targetVerdict?.status === 'pass'
      ? rgb(0.05, 0.5, 0.25)
      : targetVerdict?.status === 'warn'
        ? rgb(0.75, 0.5, 0.05)
        : rgb(0.7, 0.1, 0.1);

  text(cur, 'Verdict at target category:', font, 11);
  textAt(cur, MARGIN + 180, verdictWord, bold, 13, verdictColor);
  cur.y -= 24;

  // Composition table
  text(cur, 'Composition (parts per 1000)', bold, 12);
  cur.y -= 16;
  // Headers
  textAt(cur, MARGIN, 'Material', bold, 9);
  textAt(cur, MARGIN + 230, 'CAS', bold, 9);
  textAt(cur, MARGIN + 320, 'Dilution', bold, 9);
  textAt(cur, MARGIN + 380, 'pp1000', bold, 9);
  textAt(cur, MARGIN + 440, '% of compound', bold, 9);
  cur.y -= 4;
  line(cur);
  cur.y -= 12;
  let total = 0;
  for (const c of input.components) {
    ensure(cur, doc, font, bold, footer, 14);
    textAt(cur, MARGIN, c.name.length > 40 ? c.name.slice(0, 38) + '…' : c.name, font, 9);
    textAt(cur, MARGIN + 230, c.cas ?? '—', mono, 8);
    textAt(cur, MARGIN + 320, `${c.dilutionPct}%`, font, 9);
    textAt(cur, MARGIN + 380, c.partsPer1000.toFixed(2), mono, 9);
    textAt(cur, MARGIN + 440, pp1000ToPct(c.partsPer1000).toFixed(3) + '%', mono, 9);
    cur.y -= 12;
    total += c.partsPer1000;
  }
  cur.y -= 4;
  line(cur);
  cur.y -= 12;
  textAt(cur, MARGIN, 'Total', bold, 9);
  textAt(cur, MARGIN + 380, total.toFixed(2), bold, 9);
  textAt(cur, MARGIN + 440, pp1000ToPct(total).toFixed(3) + '%', bold, 9);
  cur.y -= 24;

  // Per-category compliance summary
  ensure(cur, doc, font, bold, footer, 60);
  text(cur, 'Compliance per IFRA category', bold, 12);
  cur.y -= 16;
  textAt(cur, MARGIN, 'Cat', bold, 9);
  textAt(cur, MARGIN + 60, 'Description', bold, 9);
  textAt(cur, MARGIN + 320, 'Status', bold, 9);
  textAt(cur, MARGIN + 400, 'Failures', bold, 9);
  cur.y -= 4;
  line(cur);
  cur.y -= 12;
  for (const cat of input.categories) {
    ensure(cur, doc, font, bold, footer, 14);
    const v = input.complianceResult.perCategory.get(cat.number);
    textAt(cur, MARGIN, cat.code, font, 9);
    textAt(cur, MARGIN + 60, cat.label.length > 40 ? cat.label.slice(0, 38) + '…' : cat.label, font, 9);
    const sCol =
      v?.status === 'pass'
        ? rgb(0.05, 0.5, 0.25)
        : v?.status === 'warn'
          ? rgb(0.75, 0.5, 0.05)
          : v?.status === 'fail'
            ? rgb(0.7, 0.1, 0.1)
            : rgb(0.4, 0.4, 0.4);
    textAt(cur, MARGIN + 320, (v?.status ?? 'unknown').toUpperCase(), bold, 9, sCol);
    textAt(cur, MARGIN + 400, String(v?.failures.length ?? 0), font, 9);
    cur.y -= 12;
  }
  cur.y -= 16;

  // Detailed failures
  const allFailures = Array.from(input.complianceResult.perCategory.values()).flatMap((v) =>
    v.failures.map((f) => ({ ...f, categoryNumber: v.categoryNumber }))
  );
  if (allFailures.length > 0) {
    ensure(cur, doc, font, bold, footer, 60);
    text(cur, 'Detailed findings', bold, 12);
    cur.y -= 16;
    // Group by standard
    const byStandard = new Map<number, typeof allFailures>();
    for (const f of allFailures) {
      const arr = byStandard.get(f.standardId) ?? [];
      arr.push(f);
      byStandard.set(f.standardId, arr);
    }
    for (const [, group] of byStandard) {
      const f0 = group[0];
      const cats = group
        .map((f) => input.categories.find((c) => c.number === f.categoryNumber)?.code ?? f.categoryNumber)
        .join(', ');
      ensure(cur, doc, font, bold, footer, 50);
      text(cur, `${f0.standardName}`, bold, 10);
      textAt(cur, MARGIN + 230, `Affects categories: ${cats}`, font, 9);
      cur.y -= 12;
      text(cur, `  Severity: ${f0.severity.replace('_', ' ')}`, font, 9);
      cur.y -= 11;
      if (f0.severity === 'over_limit' && f0.limitPct != null) {
        text(
          cur,
          `  Computed: ${fmtPct(f0.actualInProductPct)} in product · Limit: ${fmtPct(f0.limitPct)}`,
          font,
          9
        );
        cur.y -= 11;
      }
      if (f0.reason) {
        text(cur, `  Reason: ${f0.reason}`, font, 9);
        cur.y -= 11;
      }
      text(cur, `  Contributors:`, font, 9);
      cur.y -= 11;
      for (const c of f0.contributors) {
        ensure(cur, doc, font, bold, footer, 14);
        text(
          cur,
          `    • ${c.materialName} (${c.via}, ${fmtPct(c.effectivePctInCompound)} in compound)`,
          font,
          9
        );
        cur.y -= 11;
      }
      cur.y -= 6;
    }
  }

  // Engine warnings (top-level)
  if (input.complianceResult.warnings.length > 0) {
    ensure(cur, doc, font, bold, footer, 30);
    text(cur, 'Notes', bold, 12);
    cur.y -= 16;
    for (const w of input.complianceResult.warnings) {
      ensure(cur, doc, font, bold, footer, 14);
      text(cur, `• ${w}`, font, 9);
      cur.y -= 11;
    }
  }

  return doc.save();
}
